### ISSUE TITLE
TypeError: Cannot read property 'isThreadOpen' of undefined

### ISSUE THREAD

**Issue by mayfield** [ForstaLabs/relay-web-app#152]
https://sentry.io/justin-mayfield/forsta-web-messenger/issues/411908968/

```
TypeError: Cannot read property 'isThreadOpen' of undefined
  at n._handleThreadCloseControl (/@worker-service.js:1:39191)
  at n._handleControlMessage (/@worker-service.js:1:35182)
```

**Comment by mayfield** [comment]
Fixed via various refactors and other works
