### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by mayfield** [ForstaLabs/relay-web-app#271]
https://sentry.io/organizations/forsta/issues/1019121947/?referrer=github_plugin

```
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
  at Driver.read (/@static/js/app/deps.min.js:575:463)
  at Driver.execute (/@static/js/app/deps.min.js:574:670)
  at ExecutionQueue.execute (/@static/js/app/deps.min.js:580:507)
  at None (/@static/js/app/deps.min.js:581:101)
  at new Promise (<anonymous>)
...
(10 additional frame(s) were not displayed)
```

**Comment by mayfield** [comment]
This is happening again.  Let's root cause it and discuss a plan for a fix after.

**Comment by mcavoybn** [comment]
When I logged in this morning I got a message about how "IndexedDB is unavailable". For some reason it gets closed when I leave a chromium tab open with app.forsta.io running and lock my computer overnight. I have read some stackoverflow stuff about how a failed attempt to hibernate causes the issue... I'll try to find them again and put links on here. I also left a tab open again today to see if it happens again.

**Comment by mcavoybn** [comment]
Happened again today. Here are a couple screenshots i snagged of the browser console:
![indexdb_weirdness](https://user-images.githubusercontent.com/22365660/59785394-e744e800-9281-11e9-951f-11193da54a3d.png)
![more_indexdb_weirdness](https://user-images.githubusercontent.com/22365660/59785395-e7dd7e80-9281-11e9-80b7-b9882c265498.png)

The issue seems to happen when constructing a new IDBInterface in lib/backbone-backing/syncIDB. When the db goes to call execute() it throws an uncaught exception saying that the database connection has closed. 

I have also found a few similar issues here:
https://github.com/jensarps/IDBWrapper/issues/80
https://github.com/localForage/localForage/issues/581
